### ISSUE TITLE
Conflicting declarations after installing picolibc

### ISSUE THREAD

**Issue by basprins** [picolibc/picolibc#299] opened 2022-06-09 18:52 UTC
Hi,

I just compiled and installed picolibc on my PC. I already had installed the arm-none-eabi toolchain. When I compile my project now, I get conflicting declarations.

```
In file included from /usr/local/picolibc/arm-none-eabi/include/wchar.h:31,
                 from /opt/gcc-arm-none-eabi/arm-none-eabi/include/c++/10.3.1/cwchar:44,
                 from /opt/gcc-arm-none-eabi/arm-none-eabi/include/c++/10.3.1/bits/postypes.h:40,
                 from /opt/gcc-arm-none-eabi/arm-none-eabi/include/c++/10.3.1/iosfwd:40,
                 from /opt/gcc-arm-none-eabi/arm-none-eabi/include/c++/10.3.1/iterator:64,
                 from /home/bp/dev/iobox/firmware/iobox-1024/source/../../thirdparty/etl/include/etl/iterator.h:39,
                 from /home/bp/dev/iobox/firmware/iobox-1024/source/../../thirdparty/etl/include/etl/algorithm.h:44,
                 from /home/bp/dev/iobox/firmware/iobox-1024/source/../../thirdparty/etl/include/etl/basic_string.h:40,
                 from /home/bp/dev/iobox/firmware/iobox-1024/source/../../thirdparty/etl/include/etl/string.h:35,
                 from /home/bp/dev/iobox/firmware/iobox-1024/source/../../shared/valinso/framework/project_definitions.hpp:4,
                 from /home/bp/dev/iobox/firmware/shared/valinso/hal/at/at_modem.cpp:4:
/usr/local/picolibc/arm-none-eabi/include/stdio.h:300:23: error: conflicting declaration 'typedef struct __file __FILE'
```

which conflicts with

```
In file included from /opt/gcc-arm-none-eabi/arm-none-eabi/include/stdlib.h:18,
                 from /opt/gcc-arm-none-eabi/arm-none-eabi/include/c++/10.3.1/cstdlib:75,
                 from /opt/gcc-arm-none-eabi/arm-none-eabi/include/c++/10.3.1/bits/stl_algo.h:59,
                 from /opt/gcc-arm-none-eabi/arm-none-eabi/include/c++/10.3.1/algorithm:62,
                 from /home/bp/dev/iobox/firmware/shared/valinso/hal/at/at_modem.cpp:1:
/opt/gcc-arm-none-eabi/arm-none-eabi/include/sys/reent.h:292:26: note: previous declaration as 'typedef struct __sFILE __FILE'
```

Am I doing something really stupid here? I have no clue how I can resolve this. Or am I mixing things (unintended) and is there simply no way I can use picolibc in a C++ project?

**Comment by keith-packard** [comment] 2022-06-09 19:43
no, you're not doing anything wrong -- the problem is that GCC's C++ support assumes that only one C library will be installed on the system. The libstdc++ support uses a bunch of `#include_next` bits in the header files, which end up resolving to newlib headers if they're available. The easy thing to do is just  remove newlib bits from the toolchain itself; then you'll get picolibc headers instead.

Alternatively, you can use the crosstool-ng toolchain instead; that has patches to fix this issue.

**Comment by basprins** [comment] 2022-06-09 19:48
Which "bits" are you referring to here? Remove some specific headers in /opt/gcc-arm-none-eabi/arm-none-eabi/include/? Should I find files which contain the phrase `#include_next` ?

**Closed** 2022-06-09 20:29 UTC

**Comment by keith-packard** [comment] 2022-06-09 23:04
heh. you figured it out without me -- yes, just replace all include_next with include and things should be fine.
