### ISSUE TITLE
tinystdio: strtod/strtof/strtold should set errno to ERANGE on overflow

### ISSUE THREAD

**Issue by archi** [picolibc/picolibc#122] opened 2021-05-26 15:44 UTC
As the title says, C99/C11 want `strtod`, `strtof` and `strtold` to set `errno` to `ERANGE` in case of an overflow.
This does not happen, yet.

The fix for `strtod` and `strtof` should be pretty simple:
Just add `errno = ERANGE;` where `flt` is set to `INFINITY` (there are some configuration options regarding `errno`, which might need to be honored).

But for `strtold` there are already these commented out lines:
```c
275 //  if (!isfinite(flt) || flt == 0)
276 //      errno = ERANGE;
```

It is not clear to me why these are commented out, so maybe it is by intention that `errno` is not set for that family of instructions?

**Comment by keith-packard** [comment] 2021-06-05 07:47
yes, these should probably set errno to be compliant with the POSIX spec. I'm sure I left the errno setting out to avoid using errno in some application as errno requires TLS support. Feel free to construct a suitable patch and tests to make sure it works.

**Comment by keith-packard** [comment] 2021-06-07 19:15
ok, that was more of an adventure than I'd expected. The new string-to-float conversion code in tinystdio was not converting double denorm values at all (always getting zero). Turns out to be caused by a missing table entry in the conversion code.

Once that was fixed, updating these functions to set errno was easy :-)

I'll wait for the tests to pass before merging to main and closing this issue.

**Comment by archi** [comment] 2021-06-08 14:18
I ran our verification suite against the branch, and the results look good :)

**Comment by archi** [comment] 2021-06-09 13:04
I got around to look at the actual test cases (the test suite does not bother printing them). The problem simply seems to be that  the`strtoX`-family does not implement parsing of hex numbers.
I played around a bit with implementing hex numbers for `strtod`. The basic case is pretty simple, but I am not sure how best to adjust the exponent scaling in `__atod_engine` to also support the different base.
[My changes are here](https://github.com/AbsInt/picolibc/commits/strtod_hex).

Not that we need it, I can just disable the test and document the limitation ;-)

**Comment by keith-packard** [comment] 2021-06-09 16:12
__atod_engine is completely base-10/base-2 specific. We'd implement another path for base-16 support; it's far easier as there's no complicated base-conversion required with all of the error analysis required to make that exact. I've created a new issue for base-16 support in printf and scanf and will close this issue as the errno problems seem to be resolved at least. For now, please simply mark that test as unsupported until the necessary support is added to picolibc. The big reason for leaving it out is the usual one -- it's a bunch of code that most people won't want or use.

**Closed by keith-packard** 2021-06-09 16:12 UTC
